baseURL = "https://www.richardlyon.net"
languageCode = "en"
title = "Richard Lyon"
theme = "clancy"
googleAnalytics = "UA-154184871-1"

[taxonomies]
    topic = "topics"
    tag = "tags"

#################### default parameters ################################
[params]
# Meta data
description = "The personal website of Richard Lyon"
author = "Richard Lyon"